name: rfdnet
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cudatoolkit=11.0.221
  - dataclasses=0.8
  - freetype=2.10.4
  - intel-openmp=2020.2
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1j
  - pillow=8.1.2
  - pip=21.0.1
  - python=3.6.13
  - pytorch=1.7.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.2
  - tk=8.6.10
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - typing_extensions=3.7.4.3
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.12.0
    - cachetools==4.2.1
    - chardet==4.0.0
    - cycler==0.10.0
    - cython==0.29.22
    - decorator==4.4.2
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.3
    - grpcio==1.36.1
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==3.7.3
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - markdown==3.3.4
    - matplotlib==3.3.4
    - networkx==2.5
    - numba==0.53.0
    - numpy-quaternion==2021.3.17.16.51.43
    - oauthlib==3.1.0
    - pandas==1.1.5
    - plyfile==0.7.3
    - pointnet2-ops==3.0.0
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymcubes==0.1.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-image==0.17.2
    - scipy==1.5.4
    - seaborn==0.11.1
    - shapely==1.7.1
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tifffile==2020.9.3
    - tqdm==4.59.0
    - trimesh==3.9.9
    - urllib3==1.26.4
    - vtk==9.0.1
    - werkzeug==1.0.1
    - zipp==3.4.1
